export const categories = [
  { id: "all", name: "All Quotes", color: "from-gray-500 to-gray-600" },
  { id: "motivation", name: "Motivation", color: "from-orange-500 to-red-500" },
  { id: "wisdom", name: "Wisdom", color: "from-blue-500 to-cyan-500" },
  { id: "success", name: "Success", color: "from-green-500 to-emerald-500" },
  { id: "love", name: "Love", color: "from-pink-500 to-rose-500" },
  { id: "happiness", name: "Happiness", color: "from-yellow-400 to-orange-500" },
  { id: "life", name: "Life", color: "from-violet-500 to-purple-500" },
  { id: "humor", name: "Humor", color: "from-teal-400 to-green-500" },
];

export const sampleQuotes = [
  { text: "The only way to do great work is to love what you do.", author: "Steve Jobs", category: "motivation" },
  { text: "Innovation distinguishes between a leader and a follower.", author: "Steve Jobs", category: "success" },
  { text: "Stay hungry, stay foolish.", author: "Steve Jobs", category: "wisdom" },
  { text: "The future belongs to those who believe in the beauty of their dreams.", author: "Eleanor Roosevelt", category: "motivation" },
  { text: "It is during our darkest moments that we must focus to see the light.", author: "Aristotle", category: "wisdom" },
  { text: "Success is not final, failure is not fatal: it is the courage to continue that counts.", author: "Winston Churchill", category: "success" },
  { text: "The only impossible journey is the one you never begin.", author: "Tony Robbins", category: "motivation" },
  { text: "Life is what happens when you're busy making other plans.", author: "John Lennon", category: "life" },
  { text: "The purpose of our lives is to be happy.", author: "Dalai Lama", category: "happiness" },
  { text: "Get busy living or get busy dying.", author: "Stephen King", category: "life" },
  { text: "You only live once, but if you do it right, once is enough.", author: "Mae West", category: "life" },
  { text: "The best way to predict the future is to create it.", author: "Peter Drucker", category: "success" },
  { text: "Happiness is not something ready-made. It comes from your own actions.", author: "Dalai Lama", category: "happiness" },
  { text: "Love is composed of a single soul inhabiting two bodies.", author: "Aristotle", category: "love" },
  { text: "The greatest happiness you can have is knowing that you do not necessarily require happiness.", author: "William Saroyan", category: "happiness" },
  { text: "I have not failed. I've just found 10,000 ways that won't work.", author: "Thomas Edison", category: "success" },
  { text: "The mind is everything. What you think you become.", author: "Buddha", category: "wisdom" },
  { text: "Believe you can and you're halfway there.", author: "Theodore Roosevelt", category: "motivation" },
  { text: "Everything you've ever wanted is on the other side of fear.", author: "George Addair", category: "motivation" },
  { text: "Hardships often prepare ordinary people for an extraordinary destiny.", author: "C.S. Lewis", category: "wisdom" },
  { text: "Dream big and dare to fail.", author: "Norman Vaughan", category: "motivation" },
  { text: "It does not matter how slowly you go as long as you do not stop.", author: "Confucius", category: "wisdom" },
  { text: "Everything has beauty, but not everyone can see.", author: "Confucius", category: "wisdom" },
  { text: "The best time to plant a tree was 20 years ago. The second best time is now.", author: "Chinese Proverb", category: "wisdom" },
  { text: "An unexamined life is not worth living.", author: "Socrates", category: "wisdom" },
  { text: "I think, therefore I am.", author: "René Descartes", category: "wisdom" },
  { text: "Where there is love there is life.", author: "Mahatma Gandhi", category: "love" },
  { text: "Love all, trust a few, do wrong to none.", author: "William Shakespeare", category: "love" },
  { text: "To love and be loved is to feel the sun from both sides.", author: "David Viscott", category: "love" },
  { text: "I never said most of the things I said.", author: "Yogi Berra", category: "humor" },
  { text: "I'm not superstitious, but I am a little stitious.", author: "Michael Scott", category: "humor" },
  { text: "Common sense is like deodorant. The people who need it most never use it.", author: "Anonymous", category: "humor" },
];
